# Copyright © 2019 The Pokersource Project
# [This work is made available under the "Affero GPL v3".]
# Please see the file LICENSE in the source
# distribution of this software for license terms.

[package]
edition = "2018"
name = "poker_cards"
version = "1.2.0"

[dependencies]
